#!/usr/bin/env python3
"""
tests/signatures/test_yara_rules.py
-------------------------------------
Pytest suite: validates every YARA rule in signatures/signatures.yar against
the corpus generated by generate_corpus.py.

Requirements (testing-security-skill):
  * Every YARA rule has at least one triggering sample (true positive)
  * Every YARA rule has at least one non-triggering sample (no false positive)
  * Tests run in isolation — never against production signature/quarantine paths
  * New crashes must produce a regression test before being marked resolved

Install test dependencies:
  pip install pytest yara-python

Run:
  python tests/signatures/generate_corpus.py   # generate corpus first
  pytest tests/signatures/test_yara_rules.py -v
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import List

import pytest
import yara  # pip install yara-python

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT       = Path(__file__).parent.parent.parent
SIGNATURES_FILE = REPO_ROOT / "signatures" / "signatures.yar"
CORPUS_ROOT     = Path(__file__).parent
MALICIOUS_DIR   = CORPUS_ROOT / "malicious"
CLEAN_DIR       = CORPUS_ROOT / "clean"

# ---------------------------------------------------------------------------
# Compile rules once for the entire test session
# ---------------------------------------------------------------------------
@pytest.fixture(scope="session")
def compiled_rules() -> yara.Rules:
    assert SIGNATURES_FILE.exists(), f"Signature file not found: {SIGNATURES_FILE}"
    return yara.compile(str(SIGNATURES_FILE))


# ---------------------------------------------------------------------------
# Helper: run YARA scan on file content
# ---------------------------------------------------------------------------
def scan_bytes(rules: yara.Rules, data: bytes) -> List[str]:
    """Return list of matched rule identifiers."""
    matches = rules.match(data=data)
    return [m.rule for m in matches]


# ---------------------------------------------------------------------------
# Rule 1: EICAR_Test_File
# ---------------------------------------------------------------------------
class TestEICARTestFile:
    RULE_ID = "EICAR_Test_File"

    def test_triggers_on_eicar_string(self, compiled_rules):
        sample = (MALICIOUS_DIR / "eicar_test.txt").read_bytes()
        assert self.RULE_ID in scan_bytes(compiled_rules, sample), \
            "EICAR rule must match the standard EICAR test string"

    def test_no_false_positive_on_clean_text(self, compiled_rules):
        sample = (CLEAN_DIR / "eicar_clean.txt").read_bytes()
        assert self.RULE_ID not in scan_bytes(compiled_rules, sample), \
            "EICAR rule must not match a plain text file"


# ---------------------------------------------------------------------------
# Rule 2: Trojan_Generic_ObfuscatedPS1_Dropper
# ---------------------------------------------------------------------------
class TestObfuscatedPS1Dropper:
    RULE_ID = "Trojan_Generic_ObfuscatedPS1_Dropper"

    def test_triggers_on_download_cradle(self, compiled_rules):
        sample = (MALICIOUS_DIR / "ps1_dropper.ps1").read_bytes()
        assert self.RULE_ID in scan_bytes(compiled_rules, sample), \
            "PS1 dropper rule must match IEX+DownloadString+EncodedCommand pattern"

    def test_no_false_positive_on_clean_ps1(self, compiled_rules):
        sample = (CLEAN_DIR / "ps1_clean.ps1").read_bytes()
        assert self.RULE_ID not in scan_bytes(compiled_rules, sample), \
            "PS1 dropper rule must not match a plain Write-Host script"


# ---------------------------------------------------------------------------
# Rule 3: Backdoor_Linux_BashReverseShell
# ---------------------------------------------------------------------------
class TestBashReverseShell:
    RULE_ID = "Backdoor_Linux_BashReverseShell"

    def test_triggers_on_dev_tcp_redirect(self, compiled_rules):
        sample = (MALICIOUS_DIR / "revshell.sh").read_bytes()
        assert self.RULE_ID in scan_bytes(compiled_rules, sample), \
            "Reverse shell rule must match bash /dev/tcp redirect pattern"

    def test_no_false_positive_on_clean_script(self, compiled_rules):
        sample = (CLEAN_DIR / "revshell_clean.sh").read_bytes()
        assert self.RULE_ID not in scan_bytes(compiled_rules, sample), \
            "Reverse shell rule must not match a normal deployment script"


# ---------------------------------------------------------------------------
# Rule 4: Dropper_Polyglot_ELF_PE_Embed
# ---------------------------------------------------------------------------
class TestPolyglotELFPE:
    RULE_ID = "Dropper_Polyglot_ELF_PE_Embed"

    def test_triggers_on_elf_with_pe(self, compiled_rules):
        sample = (MALICIOUS_DIR / "polyglot_elf_pe.bin").read_bytes()
        assert self.RULE_ID in scan_bytes(compiled_rules, sample), \
            "Polyglot rule must match file with both ELF and PE magic headers"

    def test_no_false_positive_on_pure_elf(self, compiled_rules):
        sample = (CLEAN_DIR / "clean_elf.bin").read_bytes()
        assert self.RULE_ID not in scan_bytes(compiled_rules, sample), \
            "Polyglot rule must not match a file with ELF magic only"


# ---------------------------------------------------------------------------
# Rule 5: Loader_Generic_XOR_Shellcode_Stub
# ---------------------------------------------------------------------------
class TestXORShellcodeStub:
    RULE_ID = "Loader_Generic_XOR_Shellcode_Stub"

    def test_triggers_on_xor_stub(self, compiled_rules):
        sample = (MALICIOUS_DIR / "xor_stub.bin").read_bytes()
        assert self.RULE_ID in scan_bytes(compiled_rules, sample), \
            "XOR stub rule must match encoded shellcode decode loop pattern"

    def test_no_false_positive_on_nops(self, compiled_rules):
        sample = (CLEAN_DIR / "clean_nops.bin").read_bytes()
        assert self.RULE_ID not in scan_bytes(compiled_rules, sample), \
            "XOR stub rule must not match a NOP sled"


# ---------------------------------------------------------------------------
# Rule 6: CoinMiner_XMRig_Config_Strings
# ---------------------------------------------------------------------------
class TestXMRigCoinMiner:
    RULE_ID = "CoinMiner_XMRig_Config_Strings"

    def test_triggers_on_xmrig_user_agent(self, compiled_rules):
        sample = (MALICIOUS_DIR / "xmrig_ua.txt").read_bytes()
        assert self.RULE_ID in scan_bytes(compiled_rules, sample), \
            "XMRig rule must match XMRig/ user-agent string"

    def test_triggers_on_xmrig_config_json(self, compiled_rules):
        sample = (MALICIOUS_DIR / "xmrig_config.json").read_bytes()
        assert self.RULE_ID in scan_bytes(compiled_rules, sample), \
            "XMRig rule must match XMRig pool config JSON structure"

    def test_no_false_positive_on_clean_json(self, compiled_rules):
        sample = (CLEAN_DIR / "clean_config.json").read_bytes()
        assert self.RULE_ID not in scan_bytes(compiled_rules, sample), \
            "XMRig rule must not match unrelated JSON"


# ---------------------------------------------------------------------------
# Rule 7: Ransomware_ShadowCopy_Deletion
# ---------------------------------------------------------------------------
class TestRansomwareShadowCopy:
    RULE_ID = "Ransomware_ShadowCopy_Deletion"

    def test_triggers_on_shadow_delete_commands(self, compiled_rules):
        sample = (MALICIOUS_DIR / "ransomware_note.bat").read_bytes()
        assert self.RULE_ID in scan_bytes(compiled_rules, sample), \
            "Ransomware rule must match vssadmin+wmic delete + ransom note"

    def test_no_false_positive_on_vssadmin_list(self, compiled_rules):
        sample = (CLEAN_DIR / "vssadmin_clean.bat").read_bytes()
        assert self.RULE_ID not in scan_bytes(compiled_rules, sample), \
            "Ransomware rule must not match vssadmin list (read-only operation)"


# ---------------------------------------------------------------------------
# Corpus completeness meta-test
# ---------------------------------------------------------------------------
class TestCorpusCompleteness:
    """Sanity check: ensure corpus files actually exist before test runs."""

    EXPECTED_MALICIOUS = [
        "eicar_test.txt", "ps1_dropper.ps1", "revshell.sh",
        "polyglot_elf_pe.bin", "xor_stub.bin",
        "xmrig_ua.txt", "xmrig_config.json", "ransomware_note.bat",
    ]
    EXPECTED_CLEAN = [
        "eicar_clean.txt", "ps1_clean.ps1", "revshell_clean.sh",
        "clean_elf.bin", "clean_nops.bin",
        "clean_config.json", "vssadmin_clean.bat",
    ]

    def test_malicious_corpus_present(self):
        for name in self.EXPECTED_MALICIOUS:
            assert (MALICIOUS_DIR / name).exists(), \
                f"Missing malicious sample: {name} — run generate_corpus.py first"

    def test_clean_corpus_present(self):
        for name in self.EXPECTED_CLEAN:
            assert (CLEAN_DIR / name).exists(), \
                f"Missing clean sample: {name} — run generate_corpus.py first"
